### ISSUE TITLE
`require-barrel-import` を `warn` 以上に設定するとエラーになる

### ISSUE THREAD

**Issue by zoshigayan** [kufu/eslint-plugin-smarthr#62]
## Environment

* macOS Monteray 12.6.2
* node 18.16.0
* eslint 8.41.0
* eslint-config-smarthr 6.8.5
* eslint-plugin-smarthr 0.3.1

## How to Reproduction

こんなかんじで `.eslintrc` を設定します

```json
{
  "extends": "smarthr",
  "rules": {
    "smarthr/require-barrel-import": "warn"
  }
}
```

Lintをかけると以下エラーが発生します

```sh-session
$ ./node_modules/.bin/eslint './client/**/*.ts{,x}'

Oops! Something went wrong! :(

ESLint: 8.41.0

TypeError: Cannot convert undefined or null to object
Occurred while linting /path/to/project/client/src/path/to/Component.tsx:1
Rule: "smarthr/require-barrel-import"
    at Function.entries (<anonymous>)
    at calculateAbsoluteImportPath (/path/to/project/node_modules/eslint-plugin-smarthr/rules/require-barrel-import/index.js:9:17)
    at ImportDeclaration (/path/to/project/node_modules/eslint-plugin-smarthr/rules/require-barrel-import/index.js:143:23)
    at ruleErrorHandler (/path/to/project/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /path/to/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/path/to/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/path/to/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/path/to/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/path/to/project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

当該ルールを `off` にするとエラーは発生しなくなります。
自分の手元だと同様のバージョンを使っている場合すべてのコンポーネントに対して発生します。

### Maybe Helps

`replacePaths` が空値になっており `Object.entries` が失敗しているっぽいです。

https://github.com/kufu/eslint-plugin-smarthr/blob/2e5072ea837e9dfdb24092ea3b2dbe57f4740818/rules/require-barrel-import/index.js#L9

**Comment by AtsushiM** [comment]
@zoshigayan 
こちらtsconfig.jsonに `compilerOptions.paths` が設定されていないことが原因のようです。
nullを返すパターンの際にthrowするように修正してみました。
https://github.com/kufu/eslint-plugin-smarthr/pull/63/files
